// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6KFD9ISEe2NGadtlH94hMdiLFhN43AnQ',
    appId: '1:8198179838:web:8882dc02f6008783880eaf',
    messagingSenderId: '8198179838',
    projectId: 'chat-app-b908b',
    authDomain: 'chat-app-b908b.firebaseapp.com',
    storageBucket: 'chat-app-b908b.appspot.com',
    measurementId: 'G-SMK974XM4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlXeSJTCigu5C8pq2jHqHuIDu3_Rvv9wM',
    appId: '1:8198179838:android:73cbd1ca4d30a3bb880eaf',
    messagingSenderId: '8198179838',
    projectId: 'chat-app-b908b',
    storageBucket: 'chat-app-b908b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1X7Rbx-3TPs_UJJnXRMEiLE3FNbNB0G8',
    appId: '1:8198179838:ios:f295044a6186f0ab880eaf',
    messagingSenderId: '8198179838',
    projectId: 'chat-app-b908b',
    storageBucket: 'chat-app-b908b.appspot.com',
    iosClientId: '8198179838-ovf5h8cdrbr18d20f1iean32uutrr7bb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1X7Rbx-3TPs_UJJnXRMEiLE3FNbNB0G8',
    appId: '1:8198179838:ios:e92f01ffbbb89cef880eaf',
    messagingSenderId: '8198179838',
    projectId: 'chat-app-b908b',
    storageBucket: 'chat-app-b908b.appspot.com',
    iosClientId: '8198179838-magnl1500075gmbg9vdbnqv0n9cd7h8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
